---
title: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE,  message = FALSE, dev = "ragg_png")
```

```{r libraries}
library(tidyverse)
library(glue)
library(patchwork)
library(tidytext)
library(ggtext)
library(scales)
```

```{r data, cache=TRUE}
filelist <- dir('data') %>% keep(~str_detect(.x, 'srt'))

all_files <- map_dfr(filelist, function(x){
  data.frame(orig = readLines(glue('data/{x}'))) %>%
    filter(orig != '') %>%
    mutate(
      type = case_when(
        str_detect(orig, '^\\d+$') ~ 'block',
        str_detect(orig, '^\\d{2}:') ~ 'time',
        TRUE ~ 'text'
      ),
      new_block = cumsum((type == 'block')*1)
    ) %>%
    group_by(new_block) %>% 
    summarize(time = max(if_else(type == 'time', orig, NA_character_), na.rm = T),
              text = paste(if_else(type == 'text', orig, ''), collapse = ' ')
    ) %>%
    mutate(file = str_replace_all(x, 'Who_s', "Who's"),
           timestamp = str_extract(time, '^\\d{2}:\\d{2}:\\d{2},\\d{3}') %>%
             str_replace(',','.') %>%
             strptime(format="%H:%M:%OS")
           ) 
})

tokens <- all_files %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words)

```

```{r overall}
overall <- tokens %>%
  group_by(num = substr(file, 1, 2), ep=str_remove_all(file, '^\\d+-|.srt')) %>%
  summarize(dirty = sum(if_else(str_detect(word, 'dirt\\w?+'), 1, 0)),
            total_words = n()) %>% 
  mutate(pct = dirty / total_words,
         num = as.numeric(num)) %>%
  ggplot(aes(x = num, y = dirty)) +
    geom_line(color = '#f2d66b',lwd = 1.2) + 
    geom_point(color = '#f2d66b', size = 3) + 
    scale_x_continuous(labels = seq(1, 20, 1),
                       breaks = seq(1, 20, 1)) +
    labs(
      x = "**Episode**",
      y = "**# of Utterances**",
      title = "How <i><b>DIRTY</b></i> is Each Episode?",
      subtitle = "Number of times 'Dirty' is said per Episode"
    ) + 
    theme(
      text = element_text(color = '#f2d66b', family = 'Asap SemiCondensed'),
      axis.text = element_text(color = '#f2d66b', size = 14) ,
      axis.title.x = element_markdown(),
      axis.title.y = element_markdown(),
      plot.title.position = 'plot',
      plot.title = element_markdown(),
      plot.background = element_rect(fill = '#162647', color = '#162647'),
      panel.background = element_rect(fill = '#162647'),
      panel.grid.major.x = element_blank(), 
      panel.grid.minor.x = element_blank()
      
    )

```

```{r time_v2}

time_v2 <- tokens %>% 
  filter(str_detect(word, 'dirt\\w?+')) %>% 
  transmute(minutes = floor(minute(timestamp))) %>%
  count(minutes) %>% 
  mutate(pct = n / sum(n),
         total = sum(n),
         cuml = cumsum(pct)) %>%
  ggplot(aes(x = minutes, y = n)) + 
  geom_hline(yintercept = 5, ltw = 2, color = 'white') + 
  geom_hline(yintercept = 10, ltw = 2, color = 'white') + 
  geom_hline(yintercept = 15, ltw = 2, color = 'white') + 
  geom_hline(yintercept = 20, ltw = 2, color = 'white') + 
  geom_hline(yintercept = 25, ltw = 2, color = 'white') + 
  geom_col(fill = '#f2d66b') + 
  #geom_label_repel(aes(label = if_else(n > 10, glue("{n} ({percent(pct, accuracy = 1)})"), NA_character_))) + 
  scale_x_continuous(breaks = seq(0, 41, 2)) + 
  scale_fill_continuous(guide = 'none') + 
  coord_polar(start = -.08) + 
  annotate('richtext', color = "#f2d66b", fill = "#162647", label.color = '#162647', label = "**10**", x = 7, y = 10, angle = 30) + 
  annotate('richtext', color = "#f2d66b", fill = "#162647", label.color = '#162647', label = "**15**", x = 7, y = 15, angle = 30) + 
  annotate('richtext', color = "#f2d66b", fill = "#162647", label.color = '#162647', label = "**20**", x = 7, y = 20, angle = 30) +
  #annotate('richtext', color = "#f2d66b", fill = "#162647", label.color = '#162647', label = "**# of Utterances**", x = 8.2, y = 16, size = 3, angle = 30) +
  labs(
    title = "The <i><b>DIRTIEST</b></i> Time?",
    subtitle = "# of 'Dirty's by Minute of Episode",
    x = "**Minute of Episode**",
    y = ""
  ) + 
    theme(
      text = element_text(color = '#f2d66b', family = 'Asap SemiCondensed'),
      axis.text = element_text(color = '#f2d66b', size = 14),
      axis.text.x = element_text(face='bold'),
      axis.text.y = element_blank(),
      plot.title.position = 'plot',
      plot.title = element_markdown(),
      axis.title.x = element_markdown(),
      panel.grid.minor = element_blank(),
      panel.grid.major = element_blank(),
      plot.background = element_rect(fill = '#162647', color = '#162647'),
      panel.background = element_rect(fill = '#162647', color = '#162547'),
      axis.line.x = element_line(color = 'white')
  )


  
```

```{r bigrams}
dirty_count_bigram <- all_files %>%
  unnest_tokens(word, text, token = 'ngrams', n = 2) %>%
  filter(str_detect(word, 'dirt\\w?+')) %>%
  separate(word, into = c('w1', 'w2'), sep = ' ') %>%
  filter(!w1 %in% stop_words$word & !w2 %in% stop_words$word) %>%
  unite('word', c(w1, w2), sep = ' ') %>%
  mutate(word = str_replace_all(word, '30', 'thirty')) %>%
  count(word) %>%
  top_n(10, n) %>%
  ggplot(aes(x = fct_reorder(word, n), y = n)) + 
    geom_col(fill = '#f2d66b') +
    geom_label(aes(label = n, hjust = if_else(n < 20, 0, 1)), color = 'black', fill = 'white') + 
    labs(
        x = "",
        y = "**# of Utterances**",
        title = "The <i><b>DIRTIEST</b></i> Phrases?",
        subtitle = "Bigrams with stop words removed"
      ) + 
      scale_y_continuous(expand = c(0, 0), limits = c(0, 49)) + 
      coord_flip() + 
      theme(
        text = element_text(color = '#f2d66b', family = 'Asap SemiCondensed'),
        axis.text = element_text(color = '#f2d66b', size = 14) ,
        plot.title.position = 'plot',
        plot.title = element_markdown(),
        plot.background = element_rect(fill = '#162647', color = '#162647'),
        panel.background = element_rect(fill = '#162647'),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line.x = element_line(color = 'white'),
        axis.text.x = element_blank(),
        axis.title.x = element_markdown()
      )    
```

```{r viz,  fig.height=8, fig.width=8}
free(overall) / (dirty_count_bigram + time_v2) +
  # plot_layout(
  #   heights = c(1, 2)
  # ) +
  plot_annotation(
    title = "<span style='font-family:Roboto'>Just How Dirty is </span><span style='font-size:35px'>The Challenge: Dirty 30?</span>",
    subtitle = "Transcribing episodes using speech-to-text to analyze the <b>298</b> times cast-members said the words *'Dirty', 'Dirt', 'Dirtier', or 'Dirtiest'*",
    caption = '**Author:** JLaw',
    #Theme in Annotation Apploies ONLY to Patchwork
    theme = theme(
      plot.background = element_rect(linewidth = .9, color = 'grey80', fill = '#162647'),
      plot.title = element_markdown(family = 'Bebas Neue', color = '#f2d66b', size= 24),
      plot.subtitle = element_textbox_simple(family = 'Roboto', color = '#f2d66b', size = 11,
                                      lineheight =  1, margin = margin(0, 0, 15, 0),),
      plot.caption = element_markdown(hjust = 1, color = "#f2d66b", family = 'Roboto'),
      plot.margin = margin(c(8, 1, 0, 1))
    )
  ) 
```



