---
title: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE,  message = FALSE, dev = "ragg_png")
```

```{r libraries}
library(tidyverse)
library(ggpubr)
library(glue)
library(patchwork)
library(png)
```


```{r data_prep}
dt <- read_csv('data/c20d1f9d-b0f0-472c-844e-5d1ff942c27b.csv') %>% 
  filter(Type == 'Sleep') %>% 
  dplyr::select(Start, End)

skeleton <- tibble(
  tm = seq(
  from = ymd_hms("2023-05-21 00:00:00"),
  to = ymd_hms('2023-12-31 23:59:00'),
  by = '15 min'
))

full <- crossing(
  skeleton, dt
) %>% 
  mutate(
    state = if_else(between(tm, Start, End), 'Asleep', 'Awake')
  ) %>% 
  group_by(
    tm
  ) %>% 
  summarize(
    state = min(state)
  ) %>% 
  filter(tm >= ymd(20230522)) %>% 
  mutate(
    id = interval(min(as.Date(tm)), as.Date(tm))/ddays(1),
    tm_id = ymd_hms(paste0('2023-01-01 ', hour(tm),":", minute(tm),":", second(tm))),
    month_id = year(as.Date(tm))*100+month(as.Date(tm))
  ) %>%
  group_by(
    month_id
  ) %>% 
  mutate(id_in_month = id - min(id),
         scaled_id_in_month = id_in_month/(max(id)-min(id)) 
         ) %>% 
  ungroup()
  
```


```{r overall}
overall <-  ggplot(full) + 
    geom_line(aes(x = tm_id, y = id, color = state, group = id)) +
    # Start at 19:30 so that 7:30 is on top
    coord_polar(clip = 'off', start = ((24-7.5)/24)*360/180*pi) + 
    #0 Hrs to 24:00 Hrs in Hour Increments
    scale_x_continuous(breaks = seq(1672531200, 1672617599, 3600),
                       labels = function(x){format(as_datetime(x), "%H:%M")}) + 
    scale_color_manual(values = c("Asleep"="#35bdd4", "Awake" = "#f5f5f5")) +
    labs(color = "") + 
    theme_void() + 
    theme(
      text = element_text(size = 14, family = "Asap SemiCondensed"),
      plot.margin = margin(c(0, 10, 0, 10)),
      axis.text.x = element_text(size = 11),
      panel.grid = element_blank(),
      legend.position = 'none'
    )

```

```{r monthly}
by_month <-  ggplot(full) + 
    geom_line(aes(x = tm_id, y = scaled_id_in_month, color = state, group = id_in_month)) +
    # Start at 19:30 so that 7:30 is on top
    coord_polar(clip = 'off', start = ((24-7.5)/24)*360/180*pi) + 
    #0 Hrs to 24:00 Hrs in Hour Increments
    scale_x_continuous(breaks = seq(1672531200, 1672617599, 3600),
                       labels = function(x){format(as_datetime(x), "%H:%M")}) + 
    scale_color_manual(values = c("Asleep"="#35bdd4", "Awake" = "#f5f5f5")) +
    facet_wrap(~month_id,
               labeller = labeller(
                 month_id = function(x){
                   format(ymd(paste0(x,"01")), "%b %Y")
                 }
               ), nrow = 2) + 
    theme_void() + 
    theme(
      text = element_text(size = 14, family = "Asap SemiCondensed"),
      axis.text.x = element_blank(), #element_text(size = 12),
      panel.grid = element_blank(),
      legend.position = 'none'
    )
```


```{r final, fig.height=8, fig.width=6}
overall / by_month +
  plot_layout(
    heights = c(1, 1)
  ) +
  plot_annotation(
    title = "**Baby JLaw's Sleep Chart**",
    subtitle = glue('*May 22, 2023 - December 31, 2023*'),
    #Theme in Annotation Apploies ONLY to Patchwork
    theme = theme(
      plot.background = element_rect(linewidth = .9, color = 'grey80', fill = '#d7f1f7'),
    )
  ) & 
  #The & Theme Applies to All Subplots AND Patch Work
  theme(
    plot.margin = margin(c(5, 10, 0, 10)),
    plot.title = ggtext::element_markdown(size = 14, family = 'Roboto'),
    plot.subtitle = ggtext::element_markdown(size = 12),
    plot.caption = ggtext::element_markdown(hjust = 0),
    strip.text.x = ggtext::element_markdown(face = 'bold'),
  )

```

